[project]
name = "deconfclicting_system"
version = "0.1.0"
description = "deconfclicting_system"
requires-python = ">=3.11"
dependencies = [
    "numpy>=2.3.2",
    "pandas>=2.3.1",
    "plotly>=6.2.0",
    "streamlit>=1.47.1",
]
